version: '3'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_USER: root,
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rgeocode
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
  rgeocode:
    build: .
    image: rgeocode:latest
    environment: 
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: rgeocode
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      PORT: 7000
      # This environment variable configures the wait script
      # to wait for MySQL server to complete initializations
      # before database migrations can run
      WAIT_HOSTS: mysql:3306
    depends_on:
      - mysql
    ports:
      - 7000:7000
    command: sh -c "/wait && npm run migrate && npm start"
    restart: always